apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
  namespace: argo-cd
spec:
  project: cluster-tools

  source:
    repoURL: https://github.com/letthefireflieslive/k8s-ph.git
    targetRevision: HEAD
    path: ./manifest/argo-events

  destination:
    server: https://kubernetes.default.svc
    namespace: argo-events

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
