apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflow
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster-tools

  source:
    repoURL: https://bitbucket.webbfontaine.com/scm/proto/k8s-united.git
    targetRevision: HEAD
    path: ./ph/components/argo-workflow

  destination:
    server: https://kubernetes.default.svc
    namespace: argo-workflows

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
