apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitnami-sealed-secret
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster-infra
  source:
    repoURL: https://bitbucket.webbfontaine.com/scm/proto/k8s-united.git
    targetRevision: HEAD
    path: ./components/sealed-secrets

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
