apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: bitbucket
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    sb1-code-change:
      endpoint: /argo-events-bitbucket
      port: "12000"
      method: POST