apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBsK4gaiDsUNBUhslW6RQv9s+ATjg7v2UC9PDylUB/vbJSWNbvgu7QzilDtIvXUbSpVYxZ6NS4zPdQZ9rQpR/N1ZRXN7wA9ts6j79NhQhrntjT+gg8T7ewWqAI6YRCjSLRaSCULEcdVucvZPyZznemu5mZtaEHTQxOmxt1M79TWJqNbQMiP8MH9JZpi0jhjzOnhcWXIJ5QtoSgErxq7exTVh90R5VujxyNsIwj9fu6lB5oc42OSM68wI1qK557O9+in70/+O/0SI7gGxmAapxwWffwr+It43Z5Jx/JKVvz0oPBxoprfKMWjnNwjJBKV0rSgM4QnrQE37XuWU5hqRjoH1vtfO1hlb5zVBCxFCg8MznKL6mOz4irFdlta52lMuN5tYstxMu9Vo5fQbB5EEJBj6qXVFvfcIB13rEoATQCZ0CSrBI+zHL2pQyTtG1EQ5mlw8kf9geJ2ch7QasV35ZUagnyLoDXK6VhFKbHe0qWFGi1oOaq3tATPm6YPrq2RLbkXLqFA2KB3rjqBDLfyjvcW+k3dW5VX3FVp+fMuJgyeJ0dULY67vgNo9KgY5KagtOQIfrrLb39aFKB9RpNMkPF+fbi7ggYR/O0oqwV9y10HMT0Ya+0v1GndWxZkXX+3yYDywts31vQlycAZFB5v36HH6MQAwbsjdfTtE4y7SFqpHkVeHAH0LcWtiCRNtWAa3oo9FpmEdFhCXLW73/SguQ2f5nyrsOSRwX7w2SXn3NuWoLi7qBw5pGba
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events

