apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgAvgltf41BNrmY2XjcXvUNEz6mNp8JddbizGz6JoNp0/EQ4oosdGk5PE0uqwoJ7hQlSo7sN9AwQ2XPyT5/CHqtYbUOdU/mLYmVzDV7egg2xT4MLwNCCd+OudIA5sYsDbNN11Pd3kVp3ZDgqBgYykyA+F4WP+h6qWGOrUqSXr8k5vcTTkQRVhIYdQXUHxMpXZ29desCyPpbC1TAuVxel3AiODRL16mtby8LjBRiCWhjerE+TbuBN1AKbUk6SiuTDr4uNr4iFe644GmXDbYY2d/IMj2ySpGJg2DZ5Luo/egnpB3q//WtF8U19KjSa8VIZ3ATge3h2i8BcRwJ5zRVjaGo8DpgXRcG6aBFudPE5LvofSn+ekRbzYAfQ5OuteR1O9dBwmqYAyc2Avzx5rIcEE2UwM6j90YOjs5NqzfouAEb7JgAv6NejybD8ralQWnV7x80pS4RIPN8wl0NjP3xZACK1eWMxFSjUVi5o1lKmfTNbTZQHlsXXhgtaklTxMQSFLi5s9dMd7GeLiLMLlZOTDgfJ7ZKEiqpzFGnFU3AJ/0fUjWQJ3C3O847Sc0qH5bmt10G1mpyG2MhGap7FfJr1ggIHOb6mZF8MJPNTELindxjbzhjAqZmSDMVJeUo4XFshiQAarTC3Tz1gag6bvG+HRzAHEq7ZmWp6Ggw53wMP+Oj1WucERFT2qX1nKOag0Gn5RVDWhM/hZiufGcOWLwtNEfWKq0/Oe2H8bOPh7Xqd0t2n9fv0ywnV58Gg
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events

