apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: argo
spec:
  encryptedData:
    .dockerconfigjson: AgB1PtSMsNninaAL+6L6/0ZiN5mBPCRHmbJ3a82F9EMSbjC3HQz9HObQPEH1niOiLEFaODXpx5bIYIBZGWM4FbhFPpbri+eHZGy5UUqTNaOp+QBJxmlhMrFb+kbYEpGneaECHi84U2q/HkJFUFsTAjKfOZIJK5keqBp/80PDen14+lSnFyy8/xUcovNUG0LBXByIySLjgj9eoFwOKJEyhFb83kVIyuw+RXsK61Z2vtNAAZrlm+/lSv/yuAvs8Rhj2cXLe1SrGBKktv/k573aRN6FRcRtVTas5mSg4ZQpxdAgR68v7KTMwLcfDcoMkzgTZIRbwFOs5RtKK+/D1A5VDafFb1PQbocfrStP0CFEUdsEp5lx92FZRDvqB0swzmafcMXkclDENAsNP8S+77CDGiBmogjB2fhWC44Xjoract0A5sa4BTB/ZLJl1hN0U8DjZuWw8izCUXKoDkQoziwrHvFtPSIlFgiX0v76L1kQmckQkZfbATEcMb+DGxWi6Q9a90K3v1gmM8WGQ/jWsXwihc35e9ngigakwUARS/5iTwhcY/Ati03TCbdGeBsywZ+bhSjgpEmZ4bVtAoJteQ6eKUWeJXtuKfmWKB42GB60NxtrquI+tgFOhsd84fn4Vj8pYiYjrbRZfsL3H0ccobEyNFAPtS6XGZhb3dDcMBWbHfxFFMhQ8ZF7Ej8ggY0XQono+0iF5o5UqXqNZfueGfpFgEZp5r7h87EKx49g7pJXSWNnSkR82PWhAKck41TJntVNB6wPlkN9D/W5lN6WyXu3v+dahf7JntsUGA5Y7Szq2FKdMzluVVm22WTeP9GkuckfkBylIw7cIzH6PIWvywY3xjwI1DSdY/PGLTjxndaKVfhh
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: argo
    type: kubernetes.io/dockerconfigjson

