apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: argo-workflows
spec:
  encryptedData:
    .dockerconfigjson: AgCWDO86tLwD4Mv6mMzL3Pj0uFndnhtYUrNDfF78u3oZCf5kE82CtCHDERJW508MPCmpzP2p0cQ9kln57XJUcX8n3eKDQocH71hvxnSVBHu4OqlZN1DQXTKRgr2lUzkAi584TGCweoJ6vO2a8AVPi+AiqPswt4Yu/CoTwXaZ8i1MLgtfFSKGW8w4hAJdaRgfkc9GymxWSrDh+khrjKUFNRgGn6i5Dhm7SKhmFn5szun+xzAibAM6C1N1buh+WU9y2+e1/3CmlRWr9UOhOioi5dzCWWrDXbT11niU/y+GnXi0zuGlROox3FUs4EfBKByvXzmQi1U1x+QYleHFJntqsq8s5fTEZ6wQHeec+03Av+JAi5KKjCRZ4r+383X6/f7v884QLLuW5JY9/mwpMPQmq4lqBgcfUe5P7wzoKmsxzKn+yQEIXseukcCS2tkw2aO723Ct5aD7/rtVIwIN/9EM8ffmVvEKBC7CHkJPidC5L06HgHkiPJTwWvrO5GJUgmhIrKrxZR2+MZyuZw3E049z7od7L9jyrCDcTQ1g7L8iQL+CB3B+eYjeA5pvJD2S1EVYzlP06Vlo2UXAKa7WRuC6cec5FDpa8eobbLRlOigOXpJE6NkZSCpaiTblSuO2Rz+i6yZUsrTBDe5+fdOt2HLE3EhQC7xjJ+TclYiaHp3Gk4xtaexRJqf2pV0F0UJPD1BAi3E6HnZcfwdz76/Pu511l5mEM71b4Cw+JgPD8EqQ4DRX++YuDnkdJ+NgjBZnks5ML3bdXk6WVmL3CJQKmREvnoARejFLf8mqRwPYs6oHGBZfO3EGm3dq8PNA19h7H/GgxJBn6SmElbwuBYKxp4XXCLhMjAU98MFlFgG7l6vw1hN7
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: argo-workflows
    type: kubernetes.io/dockerconfigjson

